@startuml
|User|
start
:Выбор блюд;
:Оформление заказа;
:Опалата заказа;
:Отслеживание заказа;

|System|
:Проверка доступности заказа;
:Проверка оплаты;
:Отправка заказа ресторану;
:Оповещение курьера;

|Restaurant|
:Выполнение заказа;
:Передача заказа курьеру;

|Courier|
:Получение заказа;
:Доставка заказа;

|User|
:Получение заказа от курьера;
stop
@enduml
