@startuml
actor User
actor Restaurant
actor Courier

User --> (Вход в систему)
User --> (Просмотр меню)
User --> (Оформление заказа)
User --> (Оплата заказа)
User --> (Отслеживание заказа)

Restaurant --> (Получение заказа)
Restaurant --> (Выполнение заказа)
Restaurant --> (Выдыча заказа курьеру)

Courier --> (Получение готового заказа)
Courier --> (Доставка)
Courier --> (Обновление статуса заказа)

@enduml