@startuml
actor User
participant "App" as App
participant "Restaurant" as Restaurant
participant "Courier" as Courier

User -> App: Выбор ресторана и еды
User -> App: Оформление заказа
App -> Restaurant: Отправка нового заказа
Restaurant -> App: Подтверждение заказа
App -> User: Подверждение заказа
Restaurant -> App: Выполнение заказа
App -> Courier: Оповещение о готовности заказа
Courier -> Restaurant: Заказ о доставке
Courier -> User: Доставка заказа
@enduml