@startuml
[*] --> New
New -> Confirmed: Подтвержден рестораном
Confirmed -> Prepare: Заказ готовится
Prepare -> Done: Заказ готов к доставке
Done -> InDelivery: Заказ доставляется курьером
InDelivery -> Delivered: Заказ доставлен заказчику
InDelivery -> Canceled: Заказ отменен
[*] --> Canceled
@enduml
